name: Build and Deploy Next.js App

on:
  push:
    branches:
      - main

env:
  AWS_REGION: ${{ secrets.AWS_SSO_REGION }}
  NEXT_PUBLIC_API_URL: ${{ secrets.NEXT_PUBLIC_API_URL }}

permissions:
  id-token: write
  contents: read

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the Next.js app repository
      - name: Checkout Next.js app
        uses: actions/checkout@v3

      # Checkout the IaC repository
      - name: Checkout IaC Repository
        uses: actions/checkout@v3
        with:
          repository: greqq/terraform-aws-infrastructure
          path: iac-repo

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm install

      - name: Build Next.js app
        run: npm run build

      - name: Export Next.js app
        run: npm run export

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.AWS_ROLE }}
          role-session-name: GitHub_to_AWS_via_FederatedOIDC
          aws-region: ${{ env.AWS_REGION }}

      - name: Copy terraform.tfvars from S3 to production folder
        run: |
          aws s3 cp s3://terraform-config-cloud-resume/terraform.tfvars iac-repo/environments/production/
          aws s3 cp s3://terraform-config-cloud-resume/backend.conf iac-repo/environments/production/

      - uses: hashicorp/setup-terraform@v2

      - name: Terraform fmt
        id: fmt
        run: terraform fmt -check
        working-directory: iac-repo/environments/production
        continue-on-error: true

      - name: Terraform Init
        id: init
        run: terraform init -backend-config=backend.conf
        working-directory: iac-repo/environments/production

      - name: Terraform Validate
        id: validate
        run: terraform validate -no-color
        working-directory: iac-repo/environments/production

      - name: Terraform Plan
        id: plan
        run: terraform plan -no-color -out=tfplan
        working-directory: iac-repo/environments/production
        continue-on-error: true

      - name: Terraform Apply
        run: terraform apply -no-color tfplan
        working-directory: iac-repo/environments/production
        continue-on-error: true

      - name: Get S3 Bucket Name from Terraform Outputs
        run: |
          cd iac-repo/environments/production
          BUCKET_NAME=$(terraform-bin output -raw s3_bucket_name)
          echo "BUCKET_NAME=$BUCKET_NAME" >> $GITHUB_ENV

      - name: Upload Website Files to S3
        run: |
          aws s3 sync ./out/ s3://$BUCKET_NAME/

      # Get the CloudFront Distribution ID from Terraform outputs
      - name: Get CloudFront Distribution ID
        run: |
          cd iac-repo/environments/production
          echo "CLOUDFRONT_ID=$(terraform-bin output -raw cloudfront_distribution_id)" >> $GITHUB_ENV

      - name: Clear CDN Cache
        run: |
          aws cloudfront create-invalidation --distribution-id $CLOUDFRONT_ID --paths "/*"
